### ISSUE TITLE
Entorno

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/generador-de-memes#7]
### Pendiente

- [x] Tareas de Gulp 
   - [x] JSDocs
   - [x] JSLinter
- [x] .editorconfig
- [x] Actualizar readme

**Comment by felixrigau** [comment]
@UlisesGascon Podríamos definir una guía de estilos para codear en JavaScript. #EsLint

**Comment by UlisesGascon** [comment]
Podemos tirar con una versión que he usado para otros proyectos como base :-)

**Comment by UlisesGascon** [comment]
Tarea concluida
